# Generated by Django 6.0.4 on 2026-04-07 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0002_add_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="risk",
            name="idx_risk_category",
        ),
        migrations.RemoveIndex(
            model_name="risk",
            name="idx_risk_cat_status",
        ),
        migrations.RenameIndex(
            model_name="risk",
            new_name="risk_status_idx",
            old_name="idx_risk_status",
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(fields=["created_at"], name="risk_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(fields=["likelihood_inherent", "impact_inherent"], name="risk_score_inherent_idx"),
        ),
    ]
