#!/bin/bash
# ClaudeOS - PR 自動生成スクリプト
# Usage: ./scripts/create-pr.sh [BASE_BRANCH]

set -euo pipefail

BASE_BRANCH="${1:-main}"
BRANCH=$(git branch --show-current)

if [ "$BRANCH" = "$BASE_BRANCH" ]; then
  echo "❌ Cannot create PR from $BASE_BRANCH to $BASE_BRANCH"
  exit 1
fi

echo "🔀 Creating Pull Request..."
echo "   Branch: $BRANCH → $BASE_BRANCH"

# 変更ファイル一覧
CHANGED_FILES=$(git diff --name-only "$BASE_BRANCH"..."$BRANCH" 2>/dev/null | head -20)
FILE_COUNT=$(git diff --name-only "$BASE_BRANCH"..."$BRANCH" 2>/dev/null | wc -l)

gh pr create \
  --title "Auto PR: $BRANCH" \
  --body "$(cat <<EOF
## Summary
Auto-generated by ClaudeOS Development Pipeline

## Changes ($FILE_COUNT files)
\`\`\`
$CHANGED_FILES
\`\`\`

## Test
- [ ] Local tests passed
- [ ] Lint check passed
- [ ] Build check passed

## CI
- Pending GitHub Actions verification

---
🤖 Generated by ClaudeOS v4
EOF
)" \
  --base "$BASE_BRANCH" \
  --head "$BRANCH"

echo "✅ Pull Request created successfully."
