#!/bin/bash
# ClaudeOS - GitHub Issue 自動生成スクリプト
# Usage: ./scripts/create-issue.sh "<TITLE>" "<BODY>" [LABELS]

set -euo pipefail

TITLE="${1:?Error: TITLE is required}"
BODY="${2:-Auto-generated by ClaudeOS}"
LABELS="${3:-auto-generated}"

echo "📝 Creating Issue..."
echo "   Title: $TITLE"

gh issue create \
  --title "$TITLE" \
  --body "$BODY" \
  --label "$LABELS" 2>/dev/null || {
    echo "⚠️  Failed to create issue. Creating without labels..."
    gh issue create \
      --title "$TITLE" \
      --body "$BODY" 2>/dev/null || {
        echo "❌ Failed to create issue."
        exit 1
      }
  }

echo "✅ Issue created successfully."
