# Generated by Django 6.0.4 on 2026-04-07 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_add_scheduled_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("grc_dashboard", "経営層GRCダッシュボード"),
                    ("iso27001_annual", "ISO27001年次レポート"),
                    ("compliance_status", "規格別準拠レポート"),
                    ("risk_trend", "リスクトレンド分析"),
                    ("soa", "適用宣言書（SoA）"),
                    ("audit_report", "監査報告書"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledreport",
            index=models.Index(fields=["is_active", "next_run"], name="scheduled_report_active_next_run_idx"),
        ),
    ]
