# Generated by Django 6.0.4 on 2026-04-07 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_add_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="compliancerequirement",
            new_name="compliance_status_idx",
            old_name="idx_compliance_status",
        ),
        migrations.RenameIndex(
            model_name="compliancerequirement",
            new_name="compliance_framework_idx",
            old_name="idx_compliance_framework",
        ),
        migrations.AddIndex(
            model_name="compliancerequirement",
            index=models.Index(fields=["framework", "compliance_status"], name="compliance_framework_status_idx"),
        ),
    ]
